---
- name: Run Three playbooks on three ansible servers
  hosts: your_hosts
  tasks:
    - name run ansible command line
      ansible.builtin.command: ansible-playbook -i 172.200.126.4  ./playbook1.yml
