---
- name: Run Three playbooks on three ansible servers
  hosts: your_hosts
  tasks:
    - name run ansible command line
      ansible.builtin.command: ansible-playbook /AnsiblePlaybooks/collecting_consumers/main.yaml
